### PR TITLE
Add theme variable for variation color

### PR DESCRIPTION
**Pull request by neagle**
I've created a very minor PR to make it possible to set the color of variation labels in the theme. Let me know if you have any questions.

### CODE REVIEW

**Comment by waltheri** [comment]
Hi,

first of all, thank you very much for your interest in WGo and all your contributions. 

The option for changing color of variation labels is certainly good, however wouldn't it be better if the configuration variable was in the configuration object of the Player class instead of the board theme? I feel it's more related to the player than board itself.

I have also another question - there is a lot of pull requests now, do I have to merge them all in the specified order? Or I can merge just some of them. I would like to discuss the other a little. I am not very good at Git so I ask.

Thanks anyway.

**Comment by neagle** [comment]
Hi—thanks for getting back to me!

> first of all, thank you very much for your interest in WGo and all your contributions.

You're welcome: WGo has been invaluable to me in making GoKibitz.

> The option for changing color of variation labels is certainly good, however wouldn't it be better if the configuration variable was in the configuration object of the Player class instead of the board theme? I feel it's more related to the player than board itself.

I wouldn't be opposed to that. The reason I put it on the board theme is that the coordinates font comes from a board theme property, too, and I thought of these two as similar.

> there is a lot of pull requests now, do I have to merge them all in the specified order? Or I can merge just some of them.

All of my pull requests are independent of each other, so you can merge whichever ones you like and ask questions about whichever ones you like.

**Comment by waltheri** [comment]
Ok, for now we'll do it this way. But for the future major release I will review it.

**Comment by neagle** [comment]
Sounds good.

**Pull request merged**
